-- Generated by @zeroin.earth/supabase-query add-teams (teams schema v1).
-- Do not edit by hand; re-run the installer to update.

-- =============================================================================
-- @zeroin.earth/supabase-query — teams schema-of-record (v1).
--
-- The library OWNS this schema (migration plan §8.8): consumers *adopt* it
-- rather than designing it, which is what makes teams transportable across
-- projects. Ship it into a project with:
--
--     npx @zeroin.earth/supabase-query add-teams   # stamps a migration
--     supabase db reset                            # (or db push) applies it
--     supabase gen types typescript --local > ...  # regenerate Database types
--
-- RESOLVED design decisions this reflects (do not re-litigate — §8.8):
--   * roles are CONSUMER-defined `text[]`; the library reserves exactly one
--     structural value, 'owner', as the v1 authority anchor. No role enum.
--   * status is LIBRARY-owned + fixed: pending | active | inactive | blocked.
--   * invites are by EMAIL only → user_id is nullable (filled on accept);
--     provisioning/emailing needs the service role → the `team-invite` Edge
--     Function, not a plain RPC. Accepting is the `accept_invite` RPC.
--
-- The `sq-teams:N` table comment is a version marker the installer/hooks read
-- to detect drift.
-- =============================================================================

-- Tables ----------------------------------------------------------------------

create table public.teams (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  prefs jsonb not null default '{}',
  created_at timestamptz not null default now()
);
comment on table public.teams is 'sq-teams:1';

-- NO team_role enum: roles are consumer-defined (text[]). 'owner' is the ONLY
-- value the library reserves — assigned by create_team, gates every management
-- RPC, and cannot be stripped from the last owner.
create table public.team_members (
  id uuid primary key default gen_random_uuid(),          -- surrogate PK (user_id is nullable)
  team_id uuid not null references public.teams (id) on delete cascade,
  user_id uuid references auth.users (id) on delete cascade,  -- NULL while a pending email-invite is unclaimed
  email text,                                             -- address the invite was sent to (pending + audit)
  roles text[] not null default '{}',                     -- consumer vocabulary; 'owner' reserved
  status text not null default 'pending'
    check (status in ('pending', 'active', 'inactive', 'blocked')),
  invited_by uuid references auth.users (id),
  invite_token uuid,                                      -- claim token for the accept flow
  created_at timestamptz not null default now(),
  unique (team_id, email),                                -- one invite per email per team
  unique (team_id, user_id)                               -- Postgres treats NULLs as distinct → many pending OK; one row per user
);
create index team_members_user_id_idx on public.team_members (user_id);
create index team_members_team_id_idx on public.team_members (team_id);

-- Recursion-safe helpers ------------------------------------------------------
-- MANDATORY: a policy on `teams` that queries `team_members` plus a policy on
-- `team_members` that queries `teams` would recurse. `security definer` bypasses
-- RLS *inside* the function, breaking the cycle. Only ACTIVE memberships count.

create or replace function public.is_team_member(p_team uuid, p_user uuid default auth.uid())
  returns boolean
  language sql
  security definer
  stable
  set search_path = ''
as $$
  select exists (
    select 1 from public.team_members m
    where m.team_id = p_team and m.user_id = p_user and m.status = 'active'
  );
$$;

create or replace function public.is_team_owner(p_team uuid, p_user uuid default auth.uid())
  returns boolean
  language sql
  security definer
  stable
  set search_path = ''
as $$
  select exists (
    select 1 from public.team_members m
    where m.team_id = p_team and m.user_id = p_user
      and m.status = 'active' and 'owner' = any (m.roles)
  );
$$;

-- Count of active owners on a team — the last-owner guard rail (removing,
-- demoting, or letting the sole owner leave would orphan the team).
create or replace function public.team_active_owner_count(p_team uuid)
  returns integer
  language sql
  security definer
  stable
  set search_path = ''
as $$
  select count(*)::int from public.team_members m
  where m.team_id = p_team and m.status = 'active' and 'owner' = any (m.roles);
$$;

-- Row Level Security ----------------------------------------------------------

alter table public.teams enable row level security;
alter table public.team_members enable row level security;

-- Reads: members see their team + its roster; an invitee sees their own row.
create policy "members read team" on public.teams for select
  using (public.is_team_member(id));

create policy "members read roster" on public.team_members for select
  using (public.is_team_member(team_id) or user_id = auth.uid());

-- Team name/prefs edits + delete by owners. These are the offline-queueable
-- plain-table writes (useUpdateTeamName / useUpdateTeamPrefs / useDeleteTeam);
-- everything on team_members goes through security-definer RPCs / the Edge
-- Function, so there is deliberately no INSERT/UPDATE grant on team_members.
create policy "owners update team" on public.teams for update
  using (public.is_team_owner(id)) with check (public.is_team_owner(id));

create policy "owners delete team" on public.teams for delete
  using (public.is_team_owner(id));

-- Table-level privileges for the PostgREST API roles. Missing GRANTs surface as
-- "permission denied for table" (distinct from an RLS denial). Inserts into
-- teams happen only inside create_team (security definer), so no insert grant.
grant select, update, delete on public.teams to authenticated;
grant select on public.team_members to authenticated;

-- The service role (Edge Functions like team-invite, and server-side admin)
-- bypasses RLS but still needs table privileges. It performs the membership
-- writes that `authenticated` deliberately cannot (invites, provisioning).
grant select, insert, update, delete on public.teams to service_role;
grant select, insert, update, delete on public.team_members to service_role;

-- Management RPCs -------------------------------------------------------------
-- All are `security definer` (they must read/write rows the caller can't touch
-- under RLS), so each body MUST assert authority itself.

-- Atomic create: team + owner membership in one transaction (staged-transaction
-- replacement, §6.4). The creator becomes an ACTIVE 'owner'.
create or replace function public.create_team(p_name text, p_prefs jsonb default '{}')
  returns public.teams
  language plpgsql
  security definer
  set search_path = ''
as $$
declare
  t public.teams;
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;

  insert into public.teams (name, prefs) values (p_name, p_prefs) returning * into t;
  insert into public.team_members (team_id, user_id, email, roles, status)
    values (
      t.id,
      auth.uid(),
      (select email from auth.users where id = auth.uid()),
      array['owner'],
      'active'
    );
  return t;
end;
$$;

-- Accept an email invite: the invitee (now authenticated) claims the pending row
-- matching the token AND their own email. Sets user_id, activates, clears token.
create or replace function public.accept_invite(p_token uuid)
  returns public.team_members
  language plpgsql
  security definer
  set search_path = ''
as $$
declare
  m public.team_members;
  caller_email text;
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;

  select email into caller_email from auth.users where id = auth.uid();

  update public.team_members
    set user_id = auth.uid(), status = 'active', invite_token = null
    where invite_token = p_token
      and status = 'pending'
      and lower(email) = lower(caller_email)
    returning * into m;

  if m.id is null then
    raise exception 'invite not found for this account';
  end if;

  return m;
end;
$$;

-- Owner-only: replace a member's roles. Cannot strip 'owner' from the last owner.
create or replace function public.update_member_roles(p_member uuid, p_roles text[])
  returns public.team_members
  language plpgsql
  security definer
  set search_path = ''
as $$
declare
  m public.team_members;
begin
  select * into m from public.team_members where id = p_member;
  if m.id is null then
    raise exception 'membership not found';
  end if;
  if not public.is_team_owner(m.team_id) then
    raise exception 'only an owner may manage memberships';
  end if;

  -- Guard: demoting the last remaining owner would orphan the team.
  if 'owner' = any (m.roles)
     and not ('owner' = any (p_roles))
     and m.status = 'active'
     and public.team_active_owner_count(m.team_id) <= 1 then
    raise exception 'cannot demote the last owner';
  end if;

  update public.team_members set roles = p_roles where id = p_member returning * into m;
  return m;
end;
$$;

-- Owner-only: change a member's status (e.g. inactive/blocked, or reactivate).
create or replace function public.set_member_status(p_member uuid, p_status text)
  returns public.team_members
  language plpgsql
  security definer
  set search_path = ''
as $$
declare
  m public.team_members;
begin
  if p_status not in ('pending', 'active', 'inactive', 'blocked') then
    raise exception 'invalid status: %', p_status;
  end if;

  select * into m from public.team_members where id = p_member;
  if m.id is null then
    raise exception 'membership not found';
  end if;
  if not public.is_team_owner(m.team_id) then
    raise exception 'only an owner may manage memberships';
  end if;

  -- Guard: deactivating the last active owner would orphan the team.
  if 'owner' = any (m.roles)
     and m.status = 'active'
     and p_status <> 'active'
     and public.team_active_owner_count(m.team_id) <= 1 then
    raise exception 'cannot deactivate the last owner';
  end if;

  update public.team_members set status = p_status where id = p_member returning * into m;
  return m;
end;
$$;

-- Owner-only: remove a member. Cannot remove the last owner.
create or replace function public.remove_member(p_member uuid)
  returns void
  language plpgsql
  security definer
  set search_path = ''
as $$
declare
  m public.team_members;
begin
  select * into m from public.team_members where id = p_member;
  if m.id is null then
    raise exception 'membership not found';
  end if;
  if not public.is_team_owner(m.team_id) then
    raise exception 'only an owner may manage memberships';
  end if;

  if 'owner' = any (m.roles)
     and m.status = 'active'
     and public.team_active_owner_count(m.team_id) <= 1 then
    raise exception 'cannot remove the last owner';
  end if;

  delete from public.team_members where id = p_member;
end;
$$;

-- Self-service: leave a team. The last owner cannot leave without transferring
-- ownership first (would orphan the team).
create or replace function public.leave_team(p_team uuid)
  returns void
  language plpgsql
  security definer
  set search_path = ''
as $$
declare
  m public.team_members;
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;

  select * into m from public.team_members
    where team_id = p_team and user_id = auth.uid() and status = 'active';
  if m.id is null then
    raise exception 'you are not an active member of this team';
  end if;

  if 'owner' = any (m.roles)
     and public.team_active_owner_count(p_team) <= 1 then
    raise exception 'the last owner cannot leave; transfer ownership first';
  end if;

  delete from public.team_members where id = m.id;
end;
$$;
